### ISSUE TITLE
[WASM] Converted numbers have missing the units

### ISSUE THREAD

**Issue by Hpancha** [nventive/calculator#115] opened 2019-06-07 18:47 UTC
### **Steps To Reproduce:**

1. Visit [WASM Calculator](http://calculator-wasm-staging.azurewebsites.net/).
2. Open the Menu and select the **Data** converter.
3. Enter the numbers up to the limit then  delete some numbers and enter numbers again.
4. Then clear it using **CE** key.
5. Again enter the number and observe the  **About equal to** result.

### **Actual behavior:**

- Units are missing for some of the numbers.
- This issue is occurring with the following converters:
    - **Data**
    - **Volume**
    - **Weight and Mass**
    - **Length**

### **Expected behavior:**

- All converted numbers shows up with their respective units.

### **Attachment:**

[Missing_Units_video.zip](https://github.com/nventive/calculator/files/3267179/Missing_Units_video.zip)

### **Device and Application Information:**
 - **OS Build:** Windows 10
 - **WASM Build Version:** Version 0.1.0-uno.1+472
 - **Environment:** Firefox, Chrome and Microsoft Edge 

### **Notes:**
- To reproduce this issue, please see the attached video to get better idea.
- Crosschecked with windows calculator.

**Comment by jeromelaban** [comment] 2019-06-10 15:53
To validate after nventive/Uno#1034

**Comment by carldebilly** [comment] 2019-06-10 20:06
Duplicate of #110

**Closed as completed by carldebilly** 2019-06-10 20:06 UTC
